# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

terraform_backend_defaults:
  type: gcs
  configuration:
    bucket: # supply existing bucket to store Terraform state

vars:
  project_id:  ## Set GCP Project ID Here ##
  deployment_name: slurm-a3
  region: customer-region
  zone: customer-zone
  a3_static_cluster_size: 32
  a3_reservation_name: a3-reservation-0
  # The following variables have default values in the blueprint and are not required to be set here.
  # They are included for reference and can be uncommented to override the defaults.
  #
  # sys_net_range: 172.16.0.0/16
  # filestore_ip_range: 192.168.0.0/29
  # disk_size: 200
  # final_image_family: slurm-dlvm
  # slurm_cluster_name: slurm0
  # source_image_project_id: source-image-project-id # use value supplied by Google Cloud staff
  # source_image: source-image-name                  # use value supplied by Google Cloud staff
  # server_ip_homefs: 0.0.0.0 ## MUST set to IP address of Filestore instance from base deployment!
  # remote_mount_homefs: /nfsshare
  # local_mount_homefs: /home
  # zones: []
  # disk_size_gb: 200
  # instance_image_custom: true
  # enable_cleanup_compute: true
  # a3_partition_name: a3
  # a3_maintenance_interval: ""
  # enable_ops_agent: true
  # enable_nvidia_dcgm: true
  # localssd_mountpoint: /mnt/localssd
